  nodeRadius: 50
  boundSafety: 0
  robotSafety: 10
  obstacleScale: 10000
  gridExtend: 250
  collisionSpeedScale: 0.1
  collisionExtrapolation: 0.2

  kpPos: 0.003
  kiPos: 0.000000
  kdPos: 0.0000
  kpOrientation: 1
  kiOrientation: 0.000000
  kdOrientation: 0.0000