  nodeRadius: 50
  boundSafety: 0
  robotSafety: 100
  obstacleScale: 10000
  gridExtend: 250

  kpPos: 0.001
  kiPos: 0.000000
  kdPos: 0.0000
  kpOrientation: 0.5
  kiOrientation: 0.000000
  kdOrientation: 0.0000