cameraAddress: "224.5.23.2"
cameraOutputPort: 10020

simulationControlAddress: "localhost"
simulationControlPort: 10300

simulationRobotControlAddressBlue: "localhost"
simulationRobotControlPortBlue: 10301
simulationRobotControlAddressYellow: "localhost"
simulationRobotControlPortYellow: 10302

tritonBotAddressBlue: "localhost"
tritonBotPortBaseBlue: 10500
tritonBotAddressYellow: "localhost"
tritonBotPortBaseYellow: 10600
tritonBotPortIncr: 10