cameraOutputAddress: "224.5.23.2"
cameraOutputPort: 10020

simulationControlAddress: "localhost"
simulationControlPort: 10300

simulationRobotControlBlueAddress: "localhost"
simulationRobotControlBluePort: 10301

simulationRobotControlYellowAddress: "localhost"
simulationRobotControlYellowPort: 10302