  # Ball radius [m]
  ballRadius : 0.042672

  # Robot radius [m]
  robotRadius : 0.09
  # Robot height [m]
  robotHeight : 0.138
  # Robot mass [kg]
  robotMass : 1.5
  # Max linear kick speed [m/s]
  robotMaxLinearKickSpeed : 8
  # Max chip kick speed [m/s]
  robotMaxChipKickSpeed : 5
  # Distance from robot center to dribbler [m] (implicitly defines the opening angle and dribbler width)
  robotCenterToDribbler : 0.09

  # Max absolute speed-up acceleration [m/s^2]
  robotAccSpeedupAbsoluteMax: 10
  # Max angular speed-up acceleration [rad/s^2]
  robotAccSpeedupAngularMax : 10
  # Max absolute brake acceleration [m/s^2]
  robotAccBrakeAbsoluteMax : 10
  # Max angular brake acceleration [rad/s^2]
  robotAccBrakeAngularMax : 10
  # Max absolute velocity [m/s]
  robotVelAbsoluteMax : 5
  # Max angular velocity [rad/s]
  robotVelAngularMax : 5

  # Robot wheel angle configuration
  # all angles are relative to looking forward,
  # all wheels / angles are clockwise
  # Angle front right [rad]
  robotFrontRight : 0.785398
  # Angle back right [rad]
  robotBackRight : 2.35619
  # Angle front left [rad]
  robotBackLeft: 3.92699
  # Angle back left [rad]
  robotFrontLeft : 5.49779

  # The distance [m] from the robot center to the ball, when the ball is as close as possible to the robot.
  # The ball may be a little bit inside the roboter when looking from top, due to the dimensions of the dribbler.
  shootRadius: 0.1
  # The height of the dribbling bar from the ground [m]
  dribblerHeight: 0.1
  # The width of the dribbler itself (where the ball can be controlled), without the mechanical frame [m].
  dribblerWidth: 0.1